/* Generated by re2c 3.1 on Tue Jun  3 10:04:41 2025 */
#line 1 "pdf_lexer.re2c.c"
/*
 * MIT License
 *
 * Copyright (c) 2023 Frédéric Bour <frederic.bour@lakaban.net>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */

#include <string.h>
#include <stdbool.h>
#include <stdio.h>
#include "pdf_lexer.h"

typedef const char *cursor_t;

#line 49 "pdf_lexer.re2c.c"

#line 37 "pdf_lexer.c"
cursor_t yyt1;
cursor_t yyt2;
#line 50 "pdf_lexer.re2c.c"


#line 61 "pdf_lexer.re2c.c"


static int
pnat(cursor_t ptr, cursor_t lim)
{
  int result = 0;
  for (; ptr < lim && *ptr >= '0' && *ptr <= '9'; ptr += 1)
    result = result * 10 + (*ptr - '0');
  return result;
}

static float
pfloat(cursor_t ptr, cursor_t lim)
{
  int neg = 0;
  double result = 0;
  if (ptr < lim && *ptr == '-')
  {
    neg = 1;
    ptr += 1;
  }
  for (; ptr < lim && *ptr >= '0' && *ptr <= '9'; ptr += 1)
    result = result * 10 + (*ptr - '0');
  if (ptr < lim  && *ptr == '.')
  {
    ptr += 1;
    double pos = 0.1;
    for (; ptr < lim && *ptr >= '0' && *ptr <= '9'; ptr += 1)
    {
      result += pos * (*ptr - '0');
      pos /= 10;
    }
  }

  return neg ? -result : result;
}

const char *
pdf_op_name(enum PDF_OP op)
{
  switch (op)
  {
    case PDF_NONE:
      return "NONE";
#define CASE(name, str) case PDF_OP_##name: return "PDF_" str
      CASE(w,  "w");
      CASE(J, "J");
      CASE(j, "j");
      CASE(M, "M");
      CASE(d, "d");
      CASE(ri, "ri");
      CASE(i, "i");
      CASE(gs, "gs");
      CASE(q, "q");
      CASE(Q, "Q");
      CASE(cm, "cm");
      CASE(m, "m");
      CASE(l, "l");
      CASE(c, "c");
      CASE(v, "v");
      CASE(y, "y");
      CASE(h, "h");
      CASE(re, "re");
      CASE(S, "S");
      CASE(s, "s");
      CASE(f, "f");
      CASE(F, "F");
      CASE(f_star, "f*");
      CASE(B, "B");
      CASE(B_star, "B*");
      CASE(b, "b");
      CASE(b_star, "b*");
      CASE(n, "n");
      CASE(W, "W");
      CASE(W_star, "W*");
      CASE(BT, "BT");
      CASE(ET, "ET");
      CASE(Tc, "Tc");
      CASE(Tw, "Tw");
      CASE(Tz, "Tz");
      CASE(TL, "TL");
      CASE(Tf, "Tf");
      CASE(Tr, "Tr");
      CASE(Ts, "Ts");
      CASE(Td, "Td");
      CASE(TD, "TD");
      CASE(Tm, "Tm");
      CASE(T_star, "T*");
      CASE(Tj, "Tj");
      CASE(TJ, "TJ");
      CASE(squote, "'");
      CASE(dquote, "''");
      CASE(d0, "d0");
      CASE(d1, "d1");
      CASE(CS, "CS");
      CASE(cs, "cs");
      CASE(SC, "SC");
      CASE(sc, "sc");
      CASE(SCN, "SCN");
      CASE(scn, "scn");
      CASE(G, "G");
      CASE(g, "g");
      CASE(RG, "RG");
      CASE(rg, "rg");
      CASE(K, "K");
      CASE(k, "k");
      CASE(sh, "sh");
      CASE(Do, "Do");
      CASE(MP, "MP");
      CASE(DP, "DP");
      CASE(BMC, "BMC");
      CASE(BDC, "BDC");
      CASE(EMC, "EMC");
      CASE(BX, "BX");
      CASE(EX, "EX");
#undef CASE
    default:
      return "INVALID";
  }
}

static void vstack_push_hex(fz_context *ctx, vstack *t, int c0, int c1)
{
  if (c0 >= '0' && c0 <= '9')
    c0 = c0 - '0';
  else if (c0 >= 'a' && c0 <= 'z')
    c0 = 10 + c0 - 'a';
  else if (c0 >= 'A' && c0 <= 'Z')
    c0 = 10 + c0 - 'A';
  else
    abort();
  if (c1 >= '0' && c1 <= '9')
    c1 = c1 - '0';
  else if (c1 >= 'a' && c1 <= 'z')
    c1 = 10 + c1 - 'a';
  else if (c1 >= 'A' && c1 <= 'Z')
    c1 = 10 + c1 - 'A';
  else
    abort();

  vstack_push_char(ctx, t, c0 * 16 + c1);
}

static void
parse_hexstring(fz_context *ctx, vstack *t, cursor_t *cur, cursor_t lim)
{
  vstack_begin_hexstring(ctx, t);
  cursor_t mar, p0, p1;
  while (*cur < lim)
  {
    
#line 195 "pdf_lexer.c"
{
	int yych;
	static const unsigned char yybm[] = {
		128,   0,   0,   0,   0,   0,   0,   0, 
		  0, 128, 128,   0, 128, 128,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		128,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	yych = *cur < lim ? **cur : -1;
	if (yych <= '/') {
		if (yych <= '\v') {
			if (yych <= 0x00) goto yy1;
			if (yych <= 0x08) goto yy2;
			if (yych >= '\v') goto yy2;
		} else {
			if (yych <= '\r') goto yy1;
			if (yych != ' ') goto yy2;
		}
	} else {
		if (yych <= '@') {
			if (yych <= '9') {
				yyt1 = *cur;
				goto yy4;
			}
			if (yych == '>') goto yy5;
			goto yy2;
		} else {
			if (yych <= 'F') {
				yyt1 = *cur;
				goto yy4;
			}
			if (yych <= '`') goto yy2;
			if (yych <= 'f') {
				yyt1 = *cur;
				goto yy4;
			}
			goto yy2;
		}
	}
yy1:
	++(*cur);
#line 231 "pdf_lexer.re2c.c"
	{ continue; }
#line 267 "pdf_lexer.c"
yy2:
	++(*cur);
yy3:
#line 234 "pdf_lexer.re2c.c"
	{ goto err; }
#line 273 "pdf_lexer.c"
yy4:
	++(*cur);
	mar = *cur;
	yych = *cur < lim ? **cur : -1;
	if (yybm[0+yych] & 128) {
		goto yy6;
	}
	if (yych <= '>') {
		if (yych <= '/') goto yy3;
		if (yych <= '9') goto yy8;
		if (yych <= '=') goto yy3;
		goto yy9;
	} else {
		if (yych <= 'F') {
			if (yych <= '@') goto yy3;
			goto yy8;
		} else {
			if (yych <= '`') goto yy3;
			if (yych <= 'f') goto yy8;
			goto yy3;
		}
	}
yy5:
	++(*cur);
#line 227 "pdf_lexer.re2c.c"
	{ vstack_end_hexstring(ctx, t);
      return; }
#line 301 "pdf_lexer.c"
yy6:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yybm[0+yych] & 128) {
		goto yy6;
	}
	if (yych <= '>') {
		if (yych <= '/') goto yy7;
		if (yych <= '9') goto yy8;
		if (yych >= '>') goto yy9;
	} else {
		if (yych <= 'F') {
			if (yych >= 'A') goto yy8;
		} else {
			if (yych <= '`') goto yy7;
			if (yych <= 'f') goto yy8;
		}
	}
yy7:
	*cur = mar;
	goto yy3;
yy8:
	++(*cur);
	p0 = yyt1;
	p1 = *cur;
	p1 += -1;
#line 214 "pdf_lexer.re2c.c"
	{
      vstack_push_hex(ctx, t, *p0, *p1);
      continue;
    }
#line 333 "pdf_lexer.c"
yy9:
	++(*cur);
	p0 = yyt1;
#line 220 "pdf_lexer.re2c.c"
	{
      vstack_push_hex(ctx, t, *p0, '0');
      vstack_end_hexstring(ctx, t);
      return;
    }
#line 343 "pdf_lexer.c"
}
#line 235 "pdf_lexer.re2c.c"

  }

err:
  fz_throw(ctx, 0, "parse_hexstring: unterminated hexstring");
}

static void
sync_string(fz_context *ctx, vstack *t, cursor_t sync, cursor_t cur)
{
  vstack_push_chars(ctx, t, sync, cur - sync);
}

static void
sync_char(fz_context *ctx, vstack *t, cursor_t sync, cursor_t cur, int c)
{
  sync_string(ctx, t, sync, cur);
  vstack_push_char(ctx, t, c);
}

static void
parse_string(fz_context *ctx, vstack *t, cursor_t *cur, cursor_t lim)
{
  int nesting = 1;
  cursor_t sync = *cur;

  vstack_begin_string(ctx, t);
  while (*cur < lim)
  {
    cursor_t p0 = *cur, p1;
    
#line 377 "pdf_lexer.c"
{
	int yych;
	yych = *cur < lim ? **cur : -1;
	if (yych <= '\'') {
		if (yych <= '\n') {
			if (yych >= '\n') goto yy12;
		} else {
			if (yych == '\r') goto yy14;
		}
	} else {
		if (yych <= ')') {
			if (yych <= '(') goto yy15;
			goto yy16;
		} else {
			if (yych == '\\') goto yy17;
		}
	}
	++(*cur);
yy11:
#line 309 "pdf_lexer.re2c.c"
	{ continue; }
#line 399 "pdf_lexer.c"
yy12:
	++(*cur);
yy13:
#line 280 "pdf_lexer.re2c.c"
	{
      sync_char(ctx, t, sync, p0, '\x0A');
      sync = *cur;
      continue;
    }
#line 409 "pdf_lexer.c"
yy14:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych == '\n') goto yy12;
	goto yy13;
yy15:
	++(*cur);
#line 268 "pdf_lexer.re2c.c"
	{ nesting += 1; continue; }
#line 419 "pdf_lexer.c"
yy16:
	++(*cur);
#line 271 "pdf_lexer.re2c.c"
	{ nesting -= 1;
      if (nesting > 0)
        continue;
      sync_string(ctx, t, sync, p0);
      vstack_end_string(ctx, t);
      return;
    }
#line 430 "pdf_lexer.c"
yy17:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych <= '\\') {
		if (yych <= '\'') {
			if (yych <= '\n') {
				if (yych <= '\t') goto yy11;
				yyt1 = *cur;
			} else {
				if (yych == '\r') {
					yyt1 = *cur;
					goto yy20;
				}
				goto yy11;
			}
		} else {
			if (yych <= '/') {
				if (yych >= '*') goto yy11;
				yyt1 = *cur;
			} else {
				if (yych <= '7') {
					yyt1 = *cur;
					goto yy21;
				}
				if (yych <= '[') goto yy11;
				yyt1 = *cur;
			}
		}
	} else {
		if (yych <= 'm') {
			if (yych <= 'b') {
				if (yych <= 'a') goto yy11;
				goto yy23;
			} else {
				if (yych == 'f') goto yy24;
				goto yy11;
			}
		} else {
			if (yych <= 'r') {
				if (yych <= 'n') goto yy25;
				if (yych <= 'q') goto yy11;
				goto yy26;
			} else {
				if (yych == 't') goto yy27;
				goto yy11;
			}
		}
	}
yy18:
	++(*cur);
yy19:
	p1 = yyt1;
#line 287 "pdf_lexer.re2c.c"
	{
      sync_string(ctx, t, sync, p0);
      sync = p1;
      continue;
    }
#line 489 "pdf_lexer.c"
yy20:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych == '\n') goto yy18;
	goto yy19;
yy21:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych <= '/') goto yy22;
	if (yych <= '7') goto yy28;
yy22:
	p1 = yyt1;
#line 300 "pdf_lexer.re2c.c"
	{ int c = 0;
      for (; p1 < *cur; p1++)
        c = c * 8 + (*p1 - '0');
      sync_char(ctx, t, sync, p0, c);
      sync = *cur;
      continue;
    }
#line 510 "pdf_lexer.c"
yy23:
	++(*cur);
#line 296 "pdf_lexer.re2c.c"
	{ sync_char(ctx, t, sync, p0, '\b'); sync = *cur; continue; }
#line 515 "pdf_lexer.c"
yy24:
	++(*cur);
#line 297 "pdf_lexer.re2c.c"
	{ sync_char(ctx, t, sync, p0, '\f'); sync = *cur; continue; }
#line 520 "pdf_lexer.c"
yy25:
	++(*cur);
#line 293 "pdf_lexer.re2c.c"
	{ sync_char(ctx, t, sync, p0, '\n'); sync = *cur; continue; }
#line 525 "pdf_lexer.c"
yy26:
	++(*cur);
#line 294 "pdf_lexer.re2c.c"
	{ sync_char(ctx, t, sync, p0, '\r'); sync = *cur; continue; }
#line 530 "pdf_lexer.c"
yy27:
	++(*cur);
#line 295 "pdf_lexer.re2c.c"
	{ sync_char(ctx, t, sync, p0, '\t'); sync = *cur; continue; }
#line 535 "pdf_lexer.c"
yy28:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych <= '/') goto yy22;
	if (yych >= '8') goto yy22;
	++(*cur);
	goto yy22;
}
#line 311 "pdf_lexer.re2c.c"

  }
  fz_throw(ctx, 0, "parse_string: unterminated string");
}

static void
parse_name(fz_context *ctx, vstack *t, cursor_t *cur, cursor_t lim)
{
  vstack_begin_name(ctx, t);

  cursor_t sync = *cur;
  while (*cur < lim)
  {
    cursor_t mar, p0 = *cur;
    
#line 560 "pdf_lexer.c"
{
	int yych;
	yych = *cur < lim ? **cur : -1;
	if (yych <= '\'') {
		if (yych <= 0x1F) {
			if (yych <= '\n') {
				if (yych <= 0x00) goto yy30;
				if (yych <= 0x08) goto yy31;
			} else {
				if (yych <= '\v') goto yy31;
				if (yych >= 0x0E) goto yy31;
			}
		} else {
			if (yych <= '#') {
				if (yych <= ' ') goto yy30;
				if (yych <= '"') goto yy31;
				goto yy32;
			} else {
				if (yych != '%') goto yy31;
			}
		}
	} else {
		if (yych <= '=') {
			if (yych <= '/') {
				if (yych <= ')') goto yy30;
				if (yych <= '.') goto yy31;
			} else {
				if (yych != '<') goto yy31;
			}
		} else {
			if (yych <= '[') {
				if (yych <= '>') goto yy30;
				if (yych <= 'Z') goto yy31;
			} else {
				if (yych != ']') goto yy31;
			}
		}
	}
yy30:
	++(*cur);
#line 338 "pdf_lexer.re2c.c"
	{
        *cur = p0;
        goto done;
      }
#line 606 "pdf_lexer.c"
yy31:
	++(*cur);
#line 344 "pdf_lexer.re2c.c"
	{ continue; }
#line 611 "pdf_lexer.c"
yy32:
	++(*cur);
	mar = *cur;
	yych = *cur < lim ? **cur : -1;
	if (yych <= '@') {
		if (yych <= '/') goto yy33;
		if (yych <= '0') goto yy34;
		if (yych <= '9') goto yy36;
	} else {
		if (yych <= 'F') goto yy36;
		if (yych <= '`') goto yy33;
		if (yych <= 'f') goto yy36;
	}
yy33:
#line 328 "pdf_lexer.re2c.c"
	{ fz_throw(ctx, 0, "parse_name: NULL byte"); }
#line 628 "pdf_lexer.c"
yy34:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych <= '@') {
		if (yych <= '/') goto yy35;
		if (yych <= '0') goto yy37;
		if (yych <= '9') goto yy38;
	} else {
		if (yych <= 'F') goto yy38;
		if (yych <= '`') goto yy35;
		if (yych <= 'f') goto yy38;
	}
yy35:
	*cur = mar;
	goto yy33;
yy36:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych <= '@') {
		if (yych <= '/') goto yy35;
		if (yych <= '9') goto yy38;
		goto yy35;
	} else {
		if (yych <= 'F') goto yy38;
		if (yych <= '`') goto yy35;
		if (yych <= 'f') goto yy38;
		goto yy35;
	}
yy37:
	++(*cur);
	goto yy33;
yy38:
	++(*cur);
#line 331 "pdf_lexer.re2c.c"
	{
        sync_string(ctx, t, sync, p0);
        sync = *cur;
        vstack_push_hex(ctx, t, p0[1], p0[2]);
      }
#line 668 "pdf_lexer.c"
}
#line 345 "pdf_lexer.re2c.c"

  }

done:
  sync_string(ctx, t, sync, *cur);
  vstack_end_name(ctx, t);
}

enum PDF_OP
pdf_parse_command(fz_context *ctx, vstack *t, cursor_t *cur, cursor_t lim)
{
  cursor_t mar, p0, p1;

  while (*cur < lim)
  {
    
#line 687 "pdf_lexer.c"
{
	int yych;
	unsigned int yyaccept = 0;
	static const unsigned char yybm[] = {
		128,   0,   0,   0,   0,   0,   0,   0, 
		  0, 128, 128,   0, 128, 128,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		128,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	mar = *cur;
	yych = *cur < lim ? **cur : -1;
	switch (yych) {
		case 0x00:
		case '\t':
		case '\n':
		case '\f':
		case '\r':
		case ' ': goto yy41;
		case '\'': goto yy42;
		case '(': goto yy43;
		case '+':
		case '-':
			yyt1 = *cur;
			goto yy44;
		case '.':
			yyt1 = *cur;
			goto yy46;
		case '/': goto yy47;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
			yyt1 = *cur;
			goto yy48;
		case '<': goto yy50;
		case '>': goto yy51;
		case 'B': goto yy52;
		case 'C': goto yy54;
		case 'D': goto yy55;
		case 'E': goto yy56;
		case 'F': goto yy57;
		case 'G': goto yy58;
		case 'J': goto yy59;
		case 'K': goto yy60;
		case 'M': goto yy61;
		case 'Q': goto yy62;
		case 'R': goto yy63;
		case 'S': goto yy64;
		case 'T': goto yy65;
		case 'W': goto yy66;
		case '[': goto yy67;
		case ']': goto yy68;
		case 'b': goto yy69;
		case 'c': goto yy70;
		case 'd': goto yy71;
		case 'f': goto yy73;
		case 'g': goto yy75;
		case 'h': goto yy76;
		case 'i': goto yy77;
		case 'j': goto yy78;
		case 'k': goto yy79;
		case 'l': goto yy80;
		case 'm': goto yy81;
		case 'n': goto yy82;
		case 'q': goto yy84;
		case 'r': goto yy85;
		case 's': goto yy86;
		case 't': goto yy87;
		case 'v': goto yy88;
		case 'w': goto yy89;
		case 'y': goto yy90;
		default: goto yy40;
	}
yy40:
#line 511 "pdf_lexer.re2c.c"
	{ fz_throw(ctx, 0, "parse_command: invalid input"); }
#line 798 "pdf_lexer.c"
yy41:
	++(*cur);
#line 363 "pdf_lexer.re2c.c"
	{ continue; }
#line 803 "pdf_lexer.c"
yy42:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych == '\'') goto yy91;
#line 485 "pdf_lexer.re2c.c"
	{ return PDF_OP_squote; }
#line 810 "pdf_lexer.c"
yy43:
	++(*cur);
#line 378 "pdf_lexer.re2c.c"
	{
      parse_string(ctx, t, cur, lim);
      continue;
    }
#line 818 "pdf_lexer.c"
yy44:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych == '.') goto yy46;
	if (yych <= '/') goto yy45;
	if (yych <= '9') goto yy92;
yy45:
	*cur = mar;
	if (yyaccept <= 2) {
		if (yyaccept <= 1) {
			if (yyaccept == 0) {
				goto yy40;
			} else {
				goto yy49;
			}
		} else {
			goto yy53;
		}
	} else {
		if (yyaccept == 3) {
			goto yy74;
		} else {
			goto yy83;
		}
	}
yy46:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych <= '/') goto yy45;
	if (yych <= '9') goto yy93;
	goto yy45;
yy47:
	++(*cur);
#line 426 "pdf_lexer.re2c.c"
	{
      parse_name(ctx, t, cur, lim);
      continue;
    }
#line 857 "pdf_lexer.c"
yy48:
	yyaccept = 1;
	++(*cur);
	mar = *cur;
	yych = *cur < lim ? **cur : -1;
	if (yybm[0+yych] & 128) {
		goto yy94;
	}
	if (yych == '.') goto yy93;
	if (yych <= '/') goto yy49;
	if (yych <= '9') goto yy48;
yy49:
	p0 = yyt1;
#line 432 "pdf_lexer.re2c.c"
	{
      vstack_push_number(ctx, t, pfloat(p0, *cur));
      continue;
    }
#line 876 "pdf_lexer.c"
yy50:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych == '<') goto yy95;
#line 384 "pdf_lexer.re2c.c"
	{
      parse_hexstring(ctx, t, cur, lim);
      continue;
    }
#line 886 "pdf_lexer.c"
yy51:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych == '>') goto yy96;
	goto yy45;
yy52:
	yyaccept = 2;
	++(*cur);
	mar = *cur;
	yych = *cur < lim ? **cur : -1;
	if (yych <= 'I') {
		if (yych <= 'C') {
			if (yych == '*') goto yy97;
		} else {
			if (yych <= 'D') goto yy98;
			if (yych >= 'I') goto yy99;
		}
	} else {
		if (yych <= 'S') {
			if (yych == 'M') goto yy100;
		} else {
			if (yych <= 'T') goto yy101;
			if (yych == 'X') goto yy102;
		}
	}
yy53:
#line 463 "pdf_lexer.re2c.c"
	{ return PDF_OP_B;   }
#line 915 "pdf_lexer.c"
yy54:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych == 'S') goto yy103;
	goto yy45;
yy55:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych == 'P') goto yy104;
	if (yych == 'o') goto yy105;
	goto yy45;
yy56:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych <= 'S') {
		if (yych == 'M') goto yy106;
		goto yy45;
	} else {
		if (yych <= 'T') goto yy107;
		if (yych == 'X') goto yy108;
		goto yy45;
	}
yy57:
	++(*cur);
#line 461 "pdf_lexer.re2c.c"
	{ return PDF_OP_F;   }
#line 942 "pdf_lexer.c"
yy58:
	++(*cur);
#line 495 "pdf_lexer.re2c.c"
	{ return PDF_OP_G;   }
#line 947 "pdf_lexer.c"
yy59:
	++(*cur);
#line 441 "pdf_lexer.re2c.c"
	{ return PDF_OP_J;   }
#line 952 "pdf_lexer.c"
yy60:
	++(*cur);
#line 499 "pdf_lexer.re2c.c"
	{ return PDF_OP_K;   }
#line 957 "pdf_lexer.c"
yy61:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych == 'P') goto yy109;
#line 443 "pdf_lexer.re2c.c"
	{ return PDF_OP_M;   }
#line 964 "pdf_lexer.c"
yy62:
	++(*cur);
#line 449 "pdf_lexer.re2c.c"
	{ return PDF_OP_Q;   }
#line 969 "pdf_lexer.c"
yy63:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych == 'G') goto yy110;
	goto yy45;
yy64:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych == 'C') goto yy111;
#line 458 "pdf_lexer.re2c.c"
	{ return PDF_OP_S;   }
#line 981 "pdf_lexer.c"
yy65:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych <= 'e') {
		if (yych <= 'J') {
			if (yych <= 'C') {
				if (yych == '*') goto yy112;
				goto yy45;
			} else {
				if (yych <= 'D') goto yy113;
				if (yych <= 'I') goto yy45;
				goto yy114;
			}
		} else {
			if (yych <= 'b') {
				if (yych == 'L') goto yy115;
				goto yy45;
			} else {
				if (yych <= 'c') goto yy116;
				if (yych <= 'd') goto yy117;
				goto yy45;
			}
		}
	} else {
		if (yych <= 'q') {
			if (yych <= 'j') {
				if (yych <= 'f') goto yy118;
				if (yych <= 'i') goto yy45;
				goto yy119;
			} else {
				if (yych == 'm') goto yy120;
				goto yy45;
			}
		} else {
			if (yych <= 'v') {
				if (yych <= 'r') goto yy121;
				if (yych <= 's') goto yy122;
				goto yy45;
			} else {
				if (yych <= 'w') goto yy123;
				if (yych == 'z') goto yy124;
				goto yy45;
			}
		}
	}
yy66:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych == '*') goto yy125;
#line 468 "pdf_lexer.re2c.c"
	{ return PDF_OP_W;   }
#line 1033 "pdf_lexer.c"
yy67:
	++(*cur);
#line 402 "pdf_lexer.re2c.c"
	{
      vstack_begin_array(ctx, t);
      continue;
    }
#line 1041 "pdf_lexer.c"
yy68:
	++(*cur);
#line 408 "pdf_lexer.re2c.c"
	{
      vstack_end_array(ctx, t);
      continue;
    }
#line 1049 "pdf_lexer.c"
yy69:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych == '*') goto yy126;
#line 465 "pdf_lexer.re2c.c"
	{ return PDF_OP_b;   }
#line 1056 "pdf_lexer.c"
yy70:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych == 'm') goto yy127;
	if (yych == 's') goto yy128;
#line 453 "pdf_lexer.re2c.c"
	{ return PDF_OP_c;   }
#line 1064 "pdf_lexer.c"
yy71:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych <= '/') goto yy72;
	if (yych <= '0') goto yy129;
	if (yych <= '1') goto yy130;
yy72:
#line 444 "pdf_lexer.re2c.c"
	{ return PDF_OP_d;   }
#line 1074 "pdf_lexer.c"
yy73:
	yyaccept = 3;
	++(*cur);
	mar = *cur;
	yych = *cur < lim ? **cur : -1;
	if (yych == '*') goto yy131;
	if (yych == 'a') goto yy132;
yy74:
#line 460 "pdf_lexer.re2c.c"
	{ return PDF_OP_f;   }
#line 1085 "pdf_lexer.c"
yy75:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych == 's') goto yy133;
#line 496 "pdf_lexer.re2c.c"
	{ return PDF_OP_g;   }
#line 1092 "pdf_lexer.c"
yy76:
	++(*cur);
#line 456 "pdf_lexer.re2c.c"
	{ return PDF_OP_h;   }
#line 1097 "pdf_lexer.c"
yy77:
	++(*cur);
#line 446 "pdf_lexer.re2c.c"
	{ return PDF_OP_i;   }
#line 1102 "pdf_lexer.c"
yy78:
	++(*cur);
#line 442 "pdf_lexer.re2c.c"
	{ return PDF_OP_j;   }
#line 1107 "pdf_lexer.c"
yy79:
	++(*cur);
#line 500 "pdf_lexer.re2c.c"
	{ return PDF_OP_k;   }
#line 1112 "pdf_lexer.c"
yy80:
	++(*cur);
#line 452 "pdf_lexer.re2c.c"
	{ return PDF_OP_l;   }
#line 1117 "pdf_lexer.c"
yy81:
	++(*cur);
#line 451 "pdf_lexer.re2c.c"
	{ return PDF_OP_m;   }
#line 1122 "pdf_lexer.c"
yy82:
	yyaccept = 4;
	++(*cur);
	mar = *cur;
	yych = *cur < lim ? **cur : -1;
	if (yych == 'u') goto yy134;
yy83:
#line 467 "pdf_lexer.re2c.c"
	{ return PDF_OP_n;   }
#line 1132 "pdf_lexer.c"
yy84:
	++(*cur);
#line 448 "pdf_lexer.re2c.c"
	{ return PDF_OP_q;   }
#line 1137 "pdf_lexer.c"
yy85:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych <= 'f') {
		if (yych == 'e') goto yy135;
		goto yy45;
	} else {
		if (yych <= 'g') goto yy136;
		if (yych == 'i') goto yy137;
		goto yy45;
	}
yy86:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych == 'c') goto yy138;
	if (yych == 'h') goto yy139;
#line 459 "pdf_lexer.re2c.c"
	{ return PDF_OP_s;   }
#line 1156 "pdf_lexer.c"
yy87:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych == 'r') goto yy140;
	goto yy45;
yy88:
	++(*cur);
#line 454 "pdf_lexer.re2c.c"
	{ return PDF_OP_v;   }
#line 1166 "pdf_lexer.c"
yy89:
	++(*cur);
#line 440 "pdf_lexer.re2c.c"
	{ return PDF_OP_w;   }
#line 1171 "pdf_lexer.c"
yy90:
	++(*cur);
#line 455 "pdf_lexer.re2c.c"
	{ return PDF_OP_y;   }
#line 1176 "pdf_lexer.c"
yy91:
	++(*cur);
#line 486 "pdf_lexer.re2c.c"
	{ return PDF_OP_dquote; }
#line 1181 "pdf_lexer.c"
yy92:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych == '.') goto yy93;
	if (yych <= '/') goto yy49;
	if (yych <= '9') goto yy92;
	goto yy49;
yy93:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych <= '/') goto yy49;
	if (yych <= '9') goto yy93;
	goto yy49;
yy94:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yybm[0+yych] & 128) {
		goto yy94;
	}
	if (yych <= '/') goto yy45;
	if (yych <= '9') {
		yyt2 = *cur;
		goto yy141;
	}
	goto yy45;
yy95:
	++(*cur);
#line 390 "pdf_lexer.re2c.c"
	{
      vstack_begin_dict(ctx, t);
      continue;
    }
#line 1214 "pdf_lexer.c"
yy96:
	++(*cur);
#line 396 "pdf_lexer.re2c.c"
	{
      vstack_end_dict(ctx, t);
      continue;
    }
#line 1222 "pdf_lexer.c"
yy97:
	++(*cur);
#line 464 "pdf_lexer.re2c.c"
	{ return PDF_OP_B_star; }
#line 1227 "pdf_lexer.c"
yy98:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych == 'C') goto yy142;
	goto yy45;
yy99:
	++(*cur);
#line 438 "pdf_lexer.re2c.c"
	{ fz_throw(ctx, 0, "parse_command: BI: TODO"); }
#line 1237 "pdf_lexer.c"
yy100:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych == 'C') goto yy143;
	goto yy45;
yy101:
	++(*cur);
#line 470 "pdf_lexer.re2c.c"
	{ return PDF_OP_BT;  }
#line 1247 "pdf_lexer.c"
yy102:
	++(*cur);
#line 508 "pdf_lexer.re2c.c"
	{ return PDF_OP_BX;  }
#line 1252 "pdf_lexer.c"
yy103:
	++(*cur);
#line 489 "pdf_lexer.re2c.c"
	{ return PDF_OP_CS;  }
#line 1257 "pdf_lexer.c"
yy104:
	++(*cur);
#line 504 "pdf_lexer.re2c.c"
	{ return PDF_OP_DP;  }
#line 1262 "pdf_lexer.c"
yy105:
	++(*cur);
#line 502 "pdf_lexer.re2c.c"
	{ return PDF_OP_Do;  }
#line 1267 "pdf_lexer.c"
yy106:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych == 'C') goto yy144;
	goto yy45;
yy107:
	++(*cur);
#line 471 "pdf_lexer.re2c.c"
	{ return PDF_OP_ET;  }
#line 1277 "pdf_lexer.c"
yy108:
	++(*cur);
#line 509 "pdf_lexer.re2c.c"
	{ return PDF_OP_EX;  }
#line 1282 "pdf_lexer.c"
yy109:
	++(*cur);
#line 503 "pdf_lexer.re2c.c"
	{ return PDF_OP_MP;  }
#line 1287 "pdf_lexer.c"
yy110:
	++(*cur);
#line 497 "pdf_lexer.re2c.c"
	{ return PDF_OP_RG;  }
#line 1292 "pdf_lexer.c"
yy111:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych == 'N') goto yy145;
#line 491 "pdf_lexer.re2c.c"
	{ return PDF_OP_SC;  }
#line 1299 "pdf_lexer.c"
yy112:
	++(*cur);
#line 482 "pdf_lexer.re2c.c"
	{ return PDF_OP_T_star; }
#line 1304 "pdf_lexer.c"
yy113:
	++(*cur);
#line 480 "pdf_lexer.re2c.c"
	{ return PDF_OP_TD;  }
#line 1309 "pdf_lexer.c"
yy114:
	++(*cur);
#line 484 "pdf_lexer.re2c.c"
	{ return PDF_OP_TJ;  }
#line 1314 "pdf_lexer.c"
yy115:
	++(*cur);
#line 475 "pdf_lexer.re2c.c"
	{ return PDF_OP_TL;  }
#line 1319 "pdf_lexer.c"
yy116:
	++(*cur);
#line 472 "pdf_lexer.re2c.c"
	{ return PDF_OP_Tc;  }
#line 1324 "pdf_lexer.c"
yy117:
	++(*cur);
#line 479 "pdf_lexer.re2c.c"
	{ return PDF_OP_Td;  }
#line 1329 "pdf_lexer.c"
yy118:
	++(*cur);
#line 476 "pdf_lexer.re2c.c"
	{ return PDF_OP_Tf;  }
#line 1334 "pdf_lexer.c"
yy119:
	++(*cur);
#line 483 "pdf_lexer.re2c.c"
	{ return PDF_OP_Tj;  }
#line 1339 "pdf_lexer.c"
yy120:
	++(*cur);
#line 481 "pdf_lexer.re2c.c"
	{ return PDF_OP_Tm;  }
#line 1344 "pdf_lexer.c"
yy121:
	++(*cur);
#line 477 "pdf_lexer.re2c.c"
	{ return PDF_OP_Tr;  }
#line 1349 "pdf_lexer.c"
yy122:
	++(*cur);
#line 478 "pdf_lexer.re2c.c"
	{ return PDF_OP_Ts;  }
#line 1354 "pdf_lexer.c"
yy123:
	++(*cur);
#line 473 "pdf_lexer.re2c.c"
	{ return PDF_OP_Tw;  }
#line 1359 "pdf_lexer.c"
yy124:
	++(*cur);
#line 474 "pdf_lexer.re2c.c"
	{ return PDF_OP_Tz;  }
#line 1364 "pdf_lexer.c"
yy125:
	++(*cur);
#line 469 "pdf_lexer.re2c.c"
	{ return PDF_OP_W_star; }
#line 1369 "pdf_lexer.c"
yy126:
	++(*cur);
#line 466 "pdf_lexer.re2c.c"
	{ return PDF_OP_b_star; }
#line 1374 "pdf_lexer.c"
yy127:
	++(*cur);
#line 450 "pdf_lexer.re2c.c"
	{ return PDF_OP_cm;  }
#line 1379 "pdf_lexer.c"
yy128:
	++(*cur);
#line 490 "pdf_lexer.re2c.c"
	{ return PDF_OP_cs;  }
#line 1384 "pdf_lexer.c"
yy129:
	++(*cur);
#line 487 "pdf_lexer.re2c.c"
	{ return PDF_OP_d0;  }
#line 1389 "pdf_lexer.c"
yy130:
	++(*cur);
#line 488 "pdf_lexer.re2c.c"
	{ return PDF_OP_d1;  }
#line 1394 "pdf_lexer.c"
yy131:
	++(*cur);
#line 462 "pdf_lexer.re2c.c"
	{ return PDF_OP_f_star; }
#line 1399 "pdf_lexer.c"
yy132:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych == 'l') goto yy146;
	goto yy45;
yy133:
	++(*cur);
#line 447 "pdf_lexer.re2c.c"
	{ return PDF_OP_gs;  }
#line 1409 "pdf_lexer.c"
yy134:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych == 'l') goto yy147;
	goto yy45;
yy135:
	++(*cur);
#line 457 "pdf_lexer.re2c.c"
	{ return PDF_OP_re;  }
#line 1419 "pdf_lexer.c"
yy136:
	++(*cur);
#line 498 "pdf_lexer.re2c.c"
	{ return PDF_OP_rg;  }
#line 1424 "pdf_lexer.c"
yy137:
	++(*cur);
#line 445 "pdf_lexer.re2c.c"
	{ return PDF_OP_ri;  }
#line 1429 "pdf_lexer.c"
yy138:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych == 'n') goto yy148;
#line 492 "pdf_lexer.re2c.c"
	{ return PDF_OP_sc;  }
#line 1436 "pdf_lexer.c"
yy139:
	++(*cur);
#line 501 "pdf_lexer.re2c.c"
	{ return PDF_OP_sh;  }
#line 1441 "pdf_lexer.c"
yy140:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych == 'u') goto yy149;
	goto yy45;
yy141:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych <= '\r') {
		if (yych <= 0x08) {
			if (yych <= 0x00) goto yy150;
			goto yy45;
		} else {
			if (yych == '\v') goto yy45;
			goto yy150;
		}
	} else {
		if (yych <= ' ') {
			if (yych <= 0x1F) goto yy45;
			goto yy150;
		} else {
			if (yych <= '/') goto yy45;
			if (yych <= '9') goto yy141;
			goto yy45;
		}
	}
yy142:
	++(*cur);
#line 506 "pdf_lexer.re2c.c"
	{ return PDF_OP_BDC; }
#line 1472 "pdf_lexer.c"
yy143:
	++(*cur);
#line 505 "pdf_lexer.re2c.c"
	{ return PDF_OP_BMC; }
#line 1477 "pdf_lexer.c"
yy144:
	++(*cur);
#line 507 "pdf_lexer.re2c.c"
	{ return PDF_OP_EMC; }
#line 1482 "pdf_lexer.c"
yy145:
	++(*cur);
#line 493 "pdf_lexer.re2c.c"
	{ return PDF_OP_SCN; }
#line 1487 "pdf_lexer.c"
yy146:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych == 's') goto yy151;
	goto yy45;
yy147:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych == 'l') goto yy152;
	goto yy45;
yy148:
	++(*cur);
#line 494 "pdf_lexer.re2c.c"
	{ return PDF_OP_scn; }
#line 1502 "pdf_lexer.c"
yy149:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych == 'e') goto yy153;
	goto yy45;
yy150:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych <= '\r') {
		if (yych <= 0x08) {
			if (yych <= 0x00) goto yy150;
			goto yy45;
		} else {
			if (yych == '\v') goto yy45;
			goto yy150;
		}
	} else {
		if (yych <= ' ') {
			if (yych <= 0x1F) goto yy45;
			goto yy150;
		} else {
			if (yych == 'R') goto yy154;
			goto yy45;
		}
	}
yy151:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych == 'e') goto yy155;
	goto yy45;
yy152:
	++(*cur);
#line 420 "pdf_lexer.re2c.c"
	{
      vstack_push_null(ctx, t);
      continue;
    }
#line 1540 "pdf_lexer.c"
yy153:
	++(*cur);
#line 366 "pdf_lexer.re2c.c"
	{
      vstack_push_bool(ctx, t, 1);
      continue;
    }
#line 1548 "pdf_lexer.c"
yy154:
	++(*cur);
	yych = *cur < lim ? **cur : -1;
	if (yych <= '\v') {
		if (yych <= 0x00) goto yy156;
		if (yych <= 0x08) goto yy45;
		if (yych <= '\n') goto yy156;
		goto yy45;
	} else {
		if (yych <= '\r') goto yy156;
		if (yych == ' ') goto yy156;
		goto yy45;
	}
yy155:
	++(*cur);
#line 372 "pdf_lexer.re2c.c"
	{
      vstack_push_bool(ctx, t, 0);
      continue;
    }
#line 1569 "pdf_lexer.c"
yy156:
	++(*cur);
	p0 = yyt1;
	p1 = yyt2;
#line 414 "pdf_lexer.re2c.c"
	{
      vstack_push_ref(ctx, t, pnat(p0, lim), pnat(p1, lim));
      continue;
    }
#line 1579 "pdf_lexer.c"
}
#line 512 "pdf_lexer.re2c.c"

  }

  return PDF_NONE;
}
